### ISSUE TITLE
네이버 크롤링.

### ISSUE THREAD

**Issue by jeyraof** [sh-cho/webtoon-crawler-python#1]
안녕하세요.

저도 크롤링해서 모아두고 싶은 데이터가 있어, 크롤러를 짜는데
이 방식으로 시도하실때 캡챠가 떠서 실패하지는 않으시나요?
제가 짠것과 유사해서 여쭤보아요~

**Comment by jeyraof** [comment]
제가 실수했나봐요. 잘 됩니다. 감사합니다 ^^

**Comment by sh-cho** [comment]
로그인할때 뜨는거 말씀하시는거면 세션에 bvsd값을 추가해주셔야 캡차가 안뜨더라고요. [제 블로그](https://torbjorn.tistory.com/223)에 대충 정리해놨습니다.
